services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - postgres
    environment:
      PORT: 1513
      NODE_ENV: production

      DB_CONNECTION: postgresql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      FRONTEND_URL: ${FRONTEND_URL}
      SYNC_DB: ${SYNC_DB}
      UPLOAD_DIR: /app/uploads
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}

    volumes:
      - ./backend/uploads:/app/uploads

    # IMPORTANT: remove ports, Traefik will handle routing
    # ports:
    #   - "1513:1513"

    labels:
      - "caddy_0.encode=zstd gzip"
      - "caddy_0.handle_path.0_reverse_proxy={{upstreams 1513}}"
      - "caddy_0.handle_path=/*"
      - "caddy_0.header=-Server"
      - "caddy_0=https://api-invoice-ocr.ai-lab.id"
      - "caddy_ingress_network=w440o8wkg4ko0w0gcg80g4og"

    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_API_OCR_PROCESS_FILE: ${VITE_API_OCR_PROCESS_FILE}
        VITE_API_OCR_AUTH_TOKEN: ${VITE_API_OCR_AUTH_TOKEN}
        VITE_API_SAVE_ENDPOINT: ${VITE_API_SAVE_ENDPOINT}
        VITE_USE_MOCK_DATA: ${VITE_USE_MOCK_DATA}

    container_name: frontend

    # Vite env only works at build time
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}

    # IMPORTANT: REMOVE PORT MAPPING
    # ports:
    #   - "5173:80"

    labels:
      - "caddy_0.encode=zstd gzip"
      - "caddy_0.handle_path.0_reverse_proxy={{upstreams 80}}"
      - "caddy_0.handle_path=/*"
      - "caddy_0.header=-Server"
      - "caddy_0.try_files={path} /index.html /index.php"
      - "caddy_0=https://invoice-ocr.ai-lab.id"
      - "caddy_ingress_network=w440o8wkg4ko0w0gcg80g4og"

    restart: always

volumes:
  postgres-data: